[BinarySerialization] Refactor the existing logic
Buga1chukY/JavaPractice pull request #16
Opened 2023-11-12 13:51 UTC by Buga1chukY

2023-11-12 21:14 UTC, MLGMAG requested changes

2023-11-12 21:14 UTC, MLGMAG commented on src/main/java/com/knu/buga1chuk/serialization/ReadObject.java
>  public class ReadObject {
Change title to `ReadPersonBinaryDemo`

2023-11-12 21:14 UTC, MLGMAG commented on src/main/java/com/knu/buga1chuk/serialization/WriteObject.java
>  public class WriteObject {
Change title to `WritePersonBinaryDemo`

2023-11-12 21:14 UTC, MLGMAG commented on src/main/java/com/knu/buga1chuk/serialization/WriteObject.java
Change package title to binary

2023-11-12 21:14 UTC, MLGMAG commented on src/main/java/com/knu/buga1chuk/service/PersonBinaryService.java
> +        PersonList persons1 = new PersonList(persons);
Rename to `personList`

2023-11-12 21:14 UTC, MLGMAG commented on src/main/java/com/knu/buga1chuk/service/PersonBinaryService.java
> +        PersonList persons1 = new PersonList(persons);
Remove the assignment to the personList.

2023-11-12 21:14 UTC, MLGMAG commented on src/main/java/com/knu/buga1chuk/service/PersonBinaryService.java
> +    public static void writePerson(File file, List<Person> persons) {
Remove static

2023-11-12 21:14 UTC, MLGMAG commented on src/main/java/com/knu/buga1chuk/service/PersonBinaryService.java
> +    public static List<Person> getPersonFromFile(File file) {
Remove static

2023-11-13 12:02 UTC, Buga1chukY commented on src/main/java/com/knu/buga1chuk/serialization/ReadObject.java
>  public class ReadObject {
fix

2023-11-13 12:02 UTC, Buga1chukY commented on src/main/java/com/knu/buga1chuk/serialization/WriteObject.java
>  public class WriteObject {
fix

2023-11-13 12:03 UTC, Buga1chukY commented on src/main/java/com/knu/buga1chuk/service/PersonBinaryService.java
> +        PersonList persons1 = new PersonList(persons);
fix

2023-11-13 12:04 UTC, Buga1chukY commented on src/main/java/com/knu/buga1chuk/service/PersonBinaryService.java
> +    public static void writePerson(File file, List<Person> persons) {
fix

2023-11-13 12:04 UTC, Buga1chukY commented on src/main/java/com/knu/buga1chuk/service/PersonBinaryService.java
> +    public static List<Person> getPersonFromFile(File file) {
fix

2023-11-13 18:33 UTC, MLGMAG requested changes

2023-11-13 18:33 UTC, MLGMAG commented on src/main/java/com/knu/buga1chuk/service/PersonBinaryService.java
> +            throw new IllegalStateException();
You lost the initial exception.

2023-11-13 18:33 UTC, MLGMAG commented on src/main/java/com/knu/buga1chuk/service/PersonBinaryService.java
> +            throw new IllegalStateException();
You lost the initial exception.

2023-11-14 00:13 UTC, Buga1chukY commented on src/main/java/com/knu/buga1chuk/serialization/WriteObject.java
fix

2023-11-14 10:05 UTC, Buga1chukY commented on src/main/java/com/knu/buga1chuk/service/PersonBinaryService.java
> +            throw new IllegalStateException();
fix

2023-11-14 10:06 UTC, Buga1chukY commented on src/main/java/com/knu/buga1chuk/service/PersonBinaryService.java
> +            throw new IllegalStateException();
fix

2023-11-14 10:06 UTC, Buga1chukY commented on src/main/java/com/knu/buga1chuk/serialization/WriteObject.java
fix

2023-11-14 10:38 UTC, MLGMAG approved these changes

2023-11-14 10:40 UTC, MLGMAG requested changes
Squash and I will approve

2023-11-14 11:56 UTC, MLGMAG approved these changes

2023-11-14 12:43 UTC, merged